---
- name: Install Docker
  hosts: VM_SERVERS
  become: yes

  tasks:
    - name: Install yum utils
      yum:
        name:
        - yum-utils
        - "@Development tools"
        lock_timeout: 180

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker-CE
      yum:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: latest

    - name: Install Docker Compose
      yum:
        name:
          ["epel-release", "python-pip", "python-devel", "gcc", "python3-pip"]
        state: latest

    - name: Update python for Doker Compose
      yum: 
        name: python 
        state: latest

    - name: Install Docker Compose
      yum:
        name:
          ["epel-release", "python-pip", "python-devel", "gcc", "python3-pip"]
        state: latest

    - name: Start Docker systemctl
      ansible.builtin.systemd:
        state: started
        name: docker        
        enabled: yes

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Print service facts
      ansible.builtin.debug:
        var: ansible_facts.services['docker.service']

 #   - name: Run docker hello
  #    docker_container:
   #     name: hello-world
    #    image: hello-world
     #   status: present